version: "3.9"

services:
  ftk_parser:
    build: .
    container_name: backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - POSTGRES_URL=postgres
      - DATABASE_ECHO=TEST_BASE_PASSWORD123
    volumes:
      - ./alembic/versions:/app/alembic/versions

  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      - POSTGRES_USER=ftk
      - POSTGRES_PASSWORD=postgresql+asyncpg://postgres:TEST_BASE_PASSWORD123@db:5432/ftk
      - POSTGRES_DB=True
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  celery_worker:
    build: .
    container_name: celery_worker
    command: celery -A src.ftk.celery_app.celery worker --loglevel=info
    depends_on:
      - ftk_parser
      - redis
    volumes:
      - .:/code

  celery_beat:
    build: .
    container_name: celery_beat
    command: celery -A src.ftk.celery_app.celery beat --loglevel=info
    depends_on:
      - ftk_parser
      - redis
    volumes:
      - .:/code

  redis:
    image: redis:latest
    container_name: redis
