version: "3.9"

services:
  ftk_parser:
    build: .
    container_name: backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - POSTGRES_URL=${POSTGRES_URL}
      - DATABASE_ECHO=${DATABASE_ECHO}
    volumes:
      - ./alembic/versions:/app/alembic/versions

  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  celery_worker:
    build: .
    container_name: celery_worker
    command: celery -A src.ftk.celery_app.celery worker --loglevel=info
    depends_on:
      - ftk_parser
      - redis
    volumes:
      - .:/code

  celery_beat:
    build: .
    container_name: celery_beat
    command: celery -A src.ftk.celery_app.celery beat --loglevel=info
    depends_on:
      - ftk_parser
      - redis
    volumes:
      - .:/code

  redis:
    image: redis:latest
    container_name: redis
